<?php

namespace App\PolioDbBundle\Entity;

/**
 * CatchupDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatchupDataRepository extends \Doctrine\ORM\EntityRepository
{
}
