<?php

namespace App\PolioDbBundle\Entity;

/**
 * IcmDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcmDataRepository extends \Doctrine\ORM\EntityRepository
{
}
