<?php

namespace App\PolioDbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TempIcmDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempIcmDataRepository extends EntityRepository
{
  public function icmSyncToMaster()
  {

    $sql = "
    INSERT INTO icm_data(district_code, no_team_monitored, team_resident_area, vaccinator_trained, vacc_stage_3, team_supervised,
    team_with_chw, team_with_female, team_accom_sm, no_missed_child_novisit, no_child_seen, no_child_with_fm, no_missed_child, no_missed_10,
    campaign_id) SELECT districtCode, noTeamMonitored, teamResidentArea, vaccinatorTrained, vaccStage3, teamSupervised, teamWithChw, teamWithFemale,
    teamAccomSm, noMissedNoTeamVisit, noChildSeen, noChildWithFm, noMissedChild, noMissed10, campaignId FROM temp_icm_data
    ";

    $em = $this->getEntityManager();
    return $em->getConnection()->query($sql);
  }

  public function truncatTempIcmData()
  {

     $sql = "TRUNCATE temp_icm_data";

    $em = $this->getEntityManager();
    return $em->getConnection()->query($sql);
  }
}
